export const FIND_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const FIND_CART_SUCCESS = "ADD_TO_CART_SUCCESS";       
export const FIND_CART_FAILURE = "ADD_TO_CART_FAILURE";


export const CLEAR_CART_REQUEST = "CLEAR_CART_REQUEST";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_FAILURE = "CLEAR_CART_FAILURE"


export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";   
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const GET_ALL_CART_ITEMS_REQUEST = "GET_ALL_CART_ITEMS_REQUEST";
export const GET_ALL_CART_ITEMS_SUCCESS = "GET_ALL_CART_ITEMS_SUCCESS";
export const GET_ALL_CART_ITEMS_FAILURE = "GET_ALL_CART_ITEMS_FAILURE"


export const REMOVE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST";
export const REMOVE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAILURE = "DELETE_CART_ITEM_FAILURE"


export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST";
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";
export const UPDATE_CART_ITEM_FAILURE = "UPDATE_CART_ITEM_FAILURE"

