
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE"


export const GET_USERS_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_USERS_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_USERS_ORDERS_FAILURE = "GET_ALL_ORDERS_FAILURE"

