export const GET_RESTAURANT_ORDER_REQUEST = "GET_RESTAURANT_ORDER_REQUEST";
export const GET_RESTAURANT_ORDER_SUCCESS = "GET_RESTAURANT_ORDER_SUCCESS";
export const GET_RESTAURANT_ORDER_FAILURE = "GET_RESTAURANT_ORDER_FAILURE";


export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE"